packages:
  - 'packages/*'
  - 'apps/*'

onlyBuiltDependencies:
  - node-datachannel
  - node-pty

catalog:
  # ===== loro-extended packages =====
  "@loro-extended/change": "^5.4.2"
  "@loro-extended/repo": "^5.4.2"
  "@loro-extended/react": "^5.4.2"
  "@loro-extended/adapter-webrtc": "^5.4.2"
  "@loro-extended/adapter-indexeddb": "^5.4.2"
  loro-crdt: "^1.10.3"

  # ===== Build tools =====
  typescript: "^5.9.3"
  tsx: "^4.21.0"
  bunup: "^0.16.22"
  tsup: "^8.5.0"
  vitest: "^4.0.17"
  "@vitest/coverage-istanbul": "^3.0.4"

  # ===== AI / Agent =====
  "@anthropic-ai/claude-agent-sdk": "^0.2.39"

  # ===== Runtime dependencies =====
  pino: "^9.6.0"
  pino-pretty: "^13.0.0"
  zod: "^4.3.5"
  hono: "^4.11.3"
  nanoid: "^5.1.6"
  lz-string: "^1.5.0"

  # ===== Cloudflare =====
  wrangler: "^4.59.3"
  "@cloudflare/workers-types": "^4.20260122.0"
  "@cloudflare/vitest-pool-workers": "^0.8.0"

  # ===== Frontend =====
  react: "^19.2.3"
  react-dom: "^19.2.3"
  "@heroui/react": "3.0.0-beta.3"
  "@heroui/styles": "3.0.0-beta.3"
  react-hotkeys-hook: "^5.2.4"
  tailwindcss: "^4.1.18"
  "@tailwindcss/vite": "^4.1.18"
  vite: "^7.3.1"
  "@vitejs/plugin-react": "^5.1.2"

  # ===== Node types =====
  "@types/node": "^25.0.10"

# Named catalogs for specific version requirements
catalogs:
  # zod v3 - used by Cloudflare Workers which need zod v3 compatibility
  zod3:
    zod: "npm:zod@^3.24.2"
