packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  # ===== loro-extended packages =====
  "@loro-extended/change": "^5.4.1"
  loro-crdt: "^1.10.3"

  # ===== Build tools =====
  typescript: "^5.9.3"
  tsx: "^4.21.0"
  bunup: "^0.16.22"
  vitest: "^4.0.17"
  "@vitest/coverage-istanbul": "^3.0.4"

  # ===== Runtime dependencies =====
  zod: "^4.3.5"
  hono: "^4.11.3"
  nanoid: "^5.1.6"
  lz-string: "^1.5.0"

  # ===== Cloudflare =====
  wrangler: "^4.59.3"
  "@cloudflare/workers-types": "^4.20260122.0"
  "@cloudflare/vitest-pool-workers": "^0.8.0"

  # ===== Node types =====
  "@types/node": "^25.0.10"

# Named catalogs for specific version requirements
catalogs:
  # zod v3 - used by Cloudflare Workers which need zod v3 compatibility
  zod3:
    zod: "npm:zod@^3.24.2"
