/**
 * Branded type aliases for ID systems.
 *
 * These types use TypeScript's branded types pattern to prevent
 * accidental misuse of IDs across different systems.
 *
 * @see docs/ID-SYSTEMS-INVENTORY.md for complete documentation
 */

/**
 * Yjs awareness client ID.
 * A 32-bit integer assigned by Yjs when a Y.Doc is created.
 * Used for document synchronization and tracking connected clients.
 *
 * NOT the same as WebRTCPeerId!
 */
export type AwarenessClientId = number & {
	readonly __brand: "AwarenessClientId";
};

/**
 * y-webrtc peer ID.
 * A UUID v4 string generated by y-webrtc for each room participant.
 * Used as the key in room.webrtcConns Map.
 *
 * NOT the same as AwarenessClientId!
 */
export type WebRTCPeerId = string & { readonly __brand: "WebRTCPeerId" };

/**
 * Plan ID.
 * A nanoid (21 character) string generated when a plan is created.
 * Used in URLs, Y.Doc document names, and IndexedDB keys.
 */
export type PlanId = string & { readonly __brand: "PlanId" };

/**
 * GitHub username.
 * Used for user identity, plan ownership, and approval system.
 */
export type GitHubUsername = string & { readonly __brand: "GitHubUsername" };

/**
 * Session token.
 * A nanoid string used for authenticating MCP API requests.
 * The hash of this token is stored in the Y.Doc.
 */
export type SessionToken = string & { readonly __brand: "SessionToken" };

/**
 * Review request ID.
 * A nanoid string generated when a review is requested.
 * Used to prevent stale review decisions.
 */
export type ReviewRequestId = string & { readonly __brand: "ReviewRequestId" };

/**
 * Export ID.
 * A UUID string generated for P2P conversation transfers.
 * Used to track multi-chunk transfers.
 */
export type ExportId = string & { readonly __brand: "ExportId" };

/**
 * Creates a PlanId from a string.
 * Use this when you know the string is a valid plan ID.
 *
 * NOTE: Branded type casts are intentional - they're the only way to create branded types.
 * The eslint-disable is necessary because TypeScript's branded types pattern requires casts.
 */
export function asPlanId(id: string): PlanId {
	// eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- Branded type cast is intentional
	return id as PlanId;
}

/**
 * Creates an AwarenessClientId from a number.
 * Use this when you know the number is from awareness.clientID.
 *
 * NOTE: Branded type casts are intentional - they're the only way to create branded types.
 */
export function asAwarenessClientId(id: number): AwarenessClientId {
	// eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- Branded type cast is intentional
	return id as AwarenessClientId;
}

/**
 * Creates a WebRTCPeerId from a string.
 * Use this when you know the string is from room.peerId.
 *
 * NOTE: Branded type casts are intentional - they're the only way to create branded types.
 */
export function asWebRTCPeerId(id: string): WebRTCPeerId {
	// eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- Branded type cast is intentional
	return id as WebRTCPeerId;
}

/**
 * Creates a GitHubUsername from a string.
 * Use this when you know the string is a GitHub username.
 *
 * NOTE: Branded type casts are intentional - they're the only way to create branded types.
 */
export function asGitHubUsername(username: string): GitHubUsername {
	// eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- Branded type cast is intentional
	return username as GitHubUsername;
}
