export { assertNever } from './assert-never.js';
export type {
  A2ADataPart,
  A2AFilePart,
  A2AMessage,
  A2APart,
  A2ATextPart,
  ClaudeCodeMessage,
  ConversationExportMeta,
  ParseTranscriptResult,
} from './conversation-export.js';
export {
  A2ADataPartSchema,
  A2AFilePartSchema,
  A2AMessageSchema,
  A2APartSchema,
  A2ATextPartSchema,
  a2aToClaudeCode,
  ClaudeCodeMessageSchema,
  ConversationExportMetaSchema,
  claudeCodeToA2A,
  formatAsClaudeCodeJSONL,
  parseClaudeCodeTranscriptString,
  summarizeA2AConversation,
  validateA2AMessages,
} from './conversation-export.js';
export { formatDeliverablesForLLM } from './deliverable-formatter.js';
export { extractDeliverables } from './deliverable-parser.js';
export type { GitHubPRResponse } from './github-validation.js';
export { GitHubPRResponseSchema } from './github-validation.js';
export type {
  AgentPresence,
  CreateHookSessionRequest,
  CreateHookSessionResponse,
  CreateSubscriptionRequest,
  CreateSubscriptionResponse,
  GetReviewStatusResponse,
  HookApiError,
  RegisterServerRequest,
  RegisterServerResponse,
  ReviewComment,
  ReviewFeedback,
  UnregisterServerRequest,
  UnregisterServerResponse,
  UpdatePlanContentRequest,
  UpdatePlanContentResponse,
  UpdatePresenceRequest,
  UpdatePresenceResponse,
} from './hook-api.js';
export {
  AgentPresenceSchema,
  CreateHookSessionRequestSchema,
  CreateHookSessionResponseSchema,
  CreateSubscriptionRequestSchema,
  CreateSubscriptionResponseSchema,
  GetReviewStatusResponseSchema,
  HookApiErrorSchema,
  RegisterServerRequestSchema,
  RegisterServerResponseSchema,
  ReviewCommentSchema,
  ReviewFeedbackSchema,
  UnregisterServerRequestSchema,
  UnregisterServerResponseSchema,
  UpdatePlanContentRequestSchema,
  UpdatePlanContentResponseSchema,
  UpdatePresenceRequestSchema,
  UpdatePresenceResponseSchema,
} from './hook-api.js';
export type {
  AwarenessClientId,
  ExportId,
  GitHubUsername,
  PlanId,
  ReviewRequestId,
  SessionToken,
  WebRTCPeerId,
} from './ids.js';
export {
  asAwarenessClientId,
  asGitHubUsername,
  asPlanId,
  asWebRTCPeerId,
} from './ids.js';
export type {
  ChoiceInputRequest,
  ConfirmInputRequest,
  CreateChoiceInputParams,
  CreateConfirmInputParams,
  CreateInputRequestParams,
  CreateMultilineInputParams,
  CreateTextInputParams,
  InputRequest,
  InputRequestStatus,
  InputRequestType,
  MultilineInputRequest,
  TextInputRequest,
} from './input-request.js';
export {
  createInputRequest,
  DEFAULT_INPUT_REQUEST_TIMEOUT_SECONDS,
  InputRequestSchema,
  InputRequestStatusValues,
  InputRequestTypeValues,
} from './input-request.js';
export type {
  CreateInviteRequest,
  InviteCreatedResponse,
  InviteRedeemedNotification,
  InviteRedemption,
  InviteRedemptionResult,
  InviteRevokedResponse,
  InviteSignalingMessage,
  InviteSignalingResponse,
  InvitesListResponse,
  InviteToken,
  ListInvitesRequest,
  RedeemInviteRequest,
  RevokeInviteRequest,
} from './invite-token.js';
export {
  buildInviteUrl,
  getTokenTimeRemaining,
  InviteRedemptionSchema,
  InviteTokenSchema,
  parseInviteFromUrl,
} from './invite-token.js';
export type {
  ChunkMessage,
  ConversationExportEnd,
  ConversationExportStartMeta,
  DecodedP2PMessage,
  P2PMessageTypeValue,
} from './p2p-messages.js';
export {
  assertNeverP2PMessage,
  ChunkMessageSchema,
  ConversationExportEndSchema,
  ConversationExportStartMetaSchema,
  decodeChunkMessage,
  decodeExportEndMessage,
  decodeExportStartMessage,
  decodeP2PMessage,
  encodeChunkMessage,
  encodeExportEndMessage,
  encodeExportStartMessage,
  isConversationChunk,
  isConversationExportEnd,
  isConversationExportStart,
  isP2PConversationMessage,
  P2PMessageType,
} from './p2p-messages.js';
export type {
  AgentActivityData,
  AgentActivityType,
  Artifact,
  ArtifactType,
  ClaudeCodeOriginMetadata,
  ConversationVersion,
  CursorOriginMetadata,
  Deliverable,
  DevinOriginMetadata,
  GitHubArtifact,
  LinkedPR,
  LinkedPRStatus,
  LocalArtifact,
  OriginMetadata,
  OriginPlatform,
  PlanEvent,
  PlanEventType,
  PlanMetadata,
  PlanSnapshot,
  PlanStatusType,
  PlanViewTab,
  PRReviewComment,
  StepCompletion,
} from './plan.js';
export {
  AgentActivityDataSchema,
  AgentActivityTypes,
  ArtifactSchema,
  ClaudeCodeOriginMetadataSchema,
  ConversationVersionSchema,
  CursorOriginMetadataSchema,
  createGitHubArtifact,
  createHandedOffConversationVersion,
  createInitialConversationVersion,
  createLinkedPR,
  createLocalArtifact,
  DeliverableSchema,
  DevinOriginMetadataSchema,
  getArtifactUrl,
  isInboxWorthy,
  LinkedPRSchema,
  LinkedPRStatusValues,
  OriginMetadataSchema,
  OriginPlatformValues,
  PlanEventSchema,
  PlanEventTypes,
  PlanMetadataSchema,
  PlanSnapshotSchema,
  PlanStatusValues,
  PlanViewTabValues,
  PRReviewCommentSchema,
  parseClaudeCodeOrigin,
} from './plan.js';
export type { PlanIndexEntry } from './plan-index.js';
export {
  NON_PLAN_DB_NAMES,
  PLAN_INDEX_DOC_NAME,
  PLAN_INDEX_VIEWED_BY_KEY,
  PlanIndexEntrySchema,
} from './plan-index.js';
export {
  clearEventViewedBy,
  clearPlanIndexViewedBy,
  getAllEventViewedByForPlan,
  getAllViewedByFromIndex,
  getPlanIndex,
  getPlanIndexEntry,
  getViewedByFromIndex,
  isEventUnread,
  markEventAsViewed,
  PLAN_INDEX_EVENT_VIEWED_BY_KEY,
  removePlanIndexEntry,
  removeViewedByFromIndex,
  setPlanIndexEntry,
  touchPlanIndexEntry,
  updatePlanIndexViewedBy,
} from './plan-index-helpers.js';
export type { RoutePath } from './routes.js';
export { ROUTES } from './routes.js';
export type { CommentBody, Thread, ThreadComment } from './thread.js';
export {
  extractMentions,
  extractTextFromCommentBody,
  isThread,
  parseThreads,
  ThreadCommentSchema,
  ThreadSchema,
} from './thread.js';
export type { FormatThreadsOptions } from './thread-formatter.js';
export { formatThreadsForLLM } from './thread-formatter.js';
export type {
  AppRouter,
  ApprovalResult,
  Change,
  ChangesResponse,
  ChangeType,
  Context,
  ConversationContext,
  ConversationHandlers,
  CreateContextFn,
  DeleteSubscriptionResponse,
  HasConnectionsResponse,
  HookContext,
  HookHandlers,
  ImportConversationRequest,
  ImportConversationResponse,
  Logger,
  PlanIdInput,
  PlanStatusResponse,
  PlanStore,
  SessionContextResult,
  SetSessionTokenRequest,
  SetSessionTokenResponse,
  SubscriptionClientIdInput,
  SubscriptionCreateParams,
} from './trpc/index.js';
/*
 * NOTE: Server primitives (middleware, publicProcedure, router) NOT exported to prevent
 * bundling @trpc/server in browser builds. Server code should import from './trpc/trpc.js'
 */
export {
  appRouter,
  ChangeSchema,
  ChangesResponseSchema,
  ChangeTypeSchema,
  conversationRouter,
  DeleteSubscriptionResponseSchema,
  HasConnectionsResponseSchema,
  hookRouter,
  ImportConversationRequestSchema,
  ImportConversationResponseSchema,
  PlanIdSchema,
  PlanStatusResponseSchema,
  planRouter,
  SetSessionTokenRequestSchema,
  SetSessionTokenResponseSchema,
  SubscriptionClientIdSchema,
  subscriptionRouter,
} from './trpc/index.js';
export type {
  UrlEncodedPlan,
  UrlEncodedPlanV1,
  UrlEncodedPlanV2,
  UrlKeyVersion,
  UrlSnapshotRef,
} from './url-encoding.js';
export {
  createPlanUrl,
  createPlanUrlWithHistory,
  decodePlan,
  encodePlan,
  getPlanFromUrl,
  isUrlEncodedPlanV1,
  isUrlEncodedPlanV2,
} from './url-encoding.js';
export type { UserProfile } from './user-helpers.js';
export { createUserResolver } from './user-helpers.js';
export type {
  AnswerInputRequestResult,
  ArchiveResult,
  GetPlanMetadataResult,
  InitPlanMetadataParams,
  PlanMetadataBaseUpdate,
  StatusTransition,
  TransitionResult,
  TransitionToChangesRequested,
  TransitionToCompleted,
  TransitionToInProgress,
  TransitionToPendingReview,
} from './yjs-helpers.js';
export {
  addArtifact,
  addConversationVersion,
  addDeliverable,
  addPlanTag,
  addPRReviewComment,
  addSnapshot,
  answerInputRequest,
  approveUser,
  archivePlan,
  cancelInputRequest,
  clearAgentPresence,
  createPlanSnapshot,
  declineInputRequest,
  getAgentPresence,
  getAgentPresences,
  getAllTagsFromIndex,
  getApprovedUsers,
  getArtifacts,
  getConversationVersions,
  getDeliverables,
  getLatestSnapshot,
  getLinkedPR,
  getLinkedPRs,
  getPlanEvents,
  getPlanMetadata,
  getPlanMetadataWithValidation,
  getPlanOwnerId,
  getPRReviewComments,
  getPRReviewCommentsForPR,
  getRejectedUsers,
  getSnapshots,
  getStepCompletions,
  getViewedBy,
  initPlanMetadata,
  isApprovalRequired,
  isPlanUnread,
  isStepCompleted,
  isUserApproved,
  isUserRejected,
  linkArtifactToDeliverable,
  linkPR,
  logPlanEvent,
  markPlanAsViewed,
  markVersionHandedOff,
  rejectUser,
  removeArtifact,
  removePlanTag,
  removePRReviewComment,
  resolvePRReviewComment,
  revokeUser,
  setAgentPresence,
  setPlanMetadata,
  toggleStepCompletion,
  transitionPlanStatus,
  unarchivePlan,
  unlinkPR,
  unrejectUser,
  updateLinkedPRStatus,
  VALID_STATUS_TRANSITIONS,
} from './yjs-helpers.js';
export type { YDocKey } from './yjs-keys.js';
export { isValidYDocKey, YDOC_KEYS } from './yjs-keys.js';
