/**
 * @shipyard/loro-schema - Loro schema and document types for Shipyard
 */

export {
  type Infer,
  type InferMutableType,
  Shape,
} from '@loro-extended/change';
export type { EpochCloseCode } from './epoch.js';
export {
  buildDocumentId,
  buildTaskConvDocId,
  buildTaskMetaDocId,
  buildTaskReviewDocId,
  DEFAULT_EPOCH,
  EPOCH_CLOSE_CODES,
  formatEpochCloseReason,
  isEpochRejection,
  isEpochValid,
  parseDocumentId,
  parseEpochFromReason,
  parseEpochParam,
} from './epoch.js';
export type { SessionId, TaskId } from './ids.js';
export {
  generateSessionId,
  generateTaskId,
  LOCAL_USER_ID,
  toSessionId,
  toTaskId,
} from './ids.js';
export type { PeerRole } from './permissions.js';
export { buildShipyardPermissions } from './permissions.js';
export { extractPlanMarkdown } from './plan-helpers.js';
export {
  addTaskToIndex,
  removeTaskFromIndex,
  updateTaskInIndex,
} from './room-helpers.js';
export type {
  AnthropicLoginRequestEphemeralValue,
  AnthropicLoginResponseEphemeralValue,
  EnhancePromptRequestEphemeralValue,
  EnhancePromptResponseEphemeralValue,
  MachineCapabilitiesEphemeralShape,
  MachineCapabilitiesEphemeralValue,
  MutableTaskIndexDocument,
  TaskIndexDocument,
  TaskIndexDocumentShape,
  TaskIndexEntry,
  UserSettingsValue,
  WorktreeCreateRequestEphemeralValue,
  WorktreeCreateResponseEphemeralValue,
  WorktreeScriptValue,
  WorktreeSetupResultEphemeralValue,
  WorktreeSetupStatus,
} from './room-schema.js';
export {
  AnthropicLoginRequestEphemeral,
  AnthropicLoginResponseEphemeral,
  EnhancePromptRequestEphemeral,
  EnhancePromptResponseEphemeral,
  MachineCapabilitiesEphemeral,
  ROOM_EPHEMERAL_DECLARATIONS,
  TaskIndexDocumentSchema,
  TaskIndexEntryShape,
  UserSettingsShape,
  WORKTREE_SETUP_STATUSES,
  WorktreeCreateRequestEphemeral,
  WorktreeCreateResponseEphemeral,
  WorktreeScriptShape,
  WorktreeSetupResultEphemeral,
  WorktreeSetupStatusShape,
} from './room-schema.js';
export type {
  A2ATaskState,
  AnthropicAuthMethod,
  AnthropicAuthStatus,
  AnthropicLoginStatus,
  CommentAuthorType,
  ContentBlock,
  ContentBlockType,
  DiffComment,
  DiffCommentScope,
  DiffCommentSide,
  DiffFile,
  DiffState,
  EpochDocument,
  EpochDocumentShape,
  ImageSource,
  ImageSourceType,
  Message,
  MutableEpochDocument,
  MutableTaskConversationDocument,
  MutableTaskMetaDocument,
  MutableTaskReviewDocument,
  PermissionDecision,
  PermissionMode,
  PermissionRequest,
  PermissionResponse,
  PlanComment,
  PlanReviewStatus,
  PlanVersion,
  ReasoningEffort,
  SessionEntry,
  SessionState,
  SupportedImageMediaType,
  TaskConversationDocument,
  TaskConversationDocumentShape,
  TaskDocHandles,
  TaskMeta,
  TaskMetaDocument,
  TaskMetaDocumentShape,
  TaskReviewDocument,
  TaskReviewDocumentShape,
  ToolRiskLevel,
} from './shapes.js';
export {
  A2A_TASK_STATES,
  ANTHROPIC_AUTH_METHODS,
  ANTHROPIC_AUTH_STATUSES,
  ANTHROPIC_LOGIN_STATUSES,
  COMMENT_AUTHOR_TYPES,
  CONTENT_BLOCK_TYPES,
  ContentBlockShape,
  classifyToolRisk,
  DIFF_COMMENT_SCOPES,
  DIFF_COMMENT_SIDES,
  DiffCommentShape,
  DiffStateShape,
  EpochDocumentSchema,
  IMAGE_SOURCE_TYPES,
  MessageShape,
  PERMISSION_DECISIONS,
  PERMISSION_MODES,
  PermissionRequestEphemeral,
  PermissionResponseEphemeral,
  PLAN_REVIEW_STATUSES,
  PlanCommentShape,
  PlanVersionShape,
  REASONING_EFFORTS,
  SESSION_STATES,
  SessionEntryShape,
  SUPPORTED_IMAGE_MEDIA_TYPES,
  TaskConversationDocumentSchema,
  TaskMetaDocumentSchema,
  TaskReviewDocumentSchema,
  TERMINAL_TASK_STATES,
  TOOL_RISK_LEVELS,
} from './shapes.js';
