#!/usr/bin/env bash
set -euo pipefail

# Setup script for session-server local development
# Creates .dev.vars, generates JWT secret, applies D1 migrations

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SESSION_SERVER_DIR="$ROOT_DIR/apps/session-server"
DEV_VARS="$SESSION_SERVER_DIR/.dev.vars"

echo "=== Shipyard Session Server Setup ==="
echo ""

# Step 1: Create .dev.vars if it doesn't exist
if [ -f "$DEV_VARS" ]; then
  echo "✓ .dev.vars already exists at $DEV_VARS"
  echo "  (delete it and re-run to regenerate)"
else
  echo "Creating .dev.vars..."

  # Generate a random JWT secret
  JWT_SECRET=$(openssl rand -base64 32)

  cat > "$DEV_VARS" << VARS
# Auto-generated by scripts/setup-session-server.sh
# GitHub OAuth App credentials — see instructions below
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
JWT_SECRET=$JWT_SECRET
VARS

  echo "✓ Created .dev.vars with auto-generated JWT_SECRET"
  echo ""
  echo "⚠️  You still need to add GitHub OAuth credentials."
  echo ""
  echo "  1. Go to: https://github.com/settings/developers"
  echo "  2. Click 'New OAuth App'"
  echo "  3. Fill in:"
  echo "     - Application name: Shipyard Local Dev"
  echo "     - Homepage URL: http://localhost:4444"
  echo "     - Authorization callback URL: http://localhost:4444/auth/device/verify"
  echo "  4. Copy Client ID and Client Secret into:"
  echo "     $DEV_VARS"
  echo ""
fi

# Step 2: Apply D1 migrations locally
echo "Applying D1 migrations locally..."
cd "$SESSION_SERVER_DIR"

# wrangler d1 migrations apply requires the database name from wrangler.toml
# For local dev, --local flag uses local SQLite (no remote D1 needed)
if command -v wrangler &> /dev/null; then
  wrangler d1 migrations apply shipyard-users --local 2>/dev/null || {
    echo "  Note: If this failed, migrations may already be applied."
    echo "  wrangler dev will apply them automatically on first run."
  }
  echo "✓ D1 migrations applied locally"
else
  echo "⚠️  wrangler not found. Migrations will be applied on first 'wrangler dev' run."
  echo "  Install with: pnpm add -g wrangler"
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Add GitHub OAuth credentials to $DEV_VARS (if not done)"
echo "  2. Start the server: pnpm dev:session-server"
echo "  3. Login the daemon: shipyard login"
echo ""
