#!/usr/bin/env bash
set -euo pipefail

# Setup script for session-server local development
# Creates .dev.vars, generates JWT secret, applies D1 migrations

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SESSION_SERVER_DIR="$ROOT_DIR/apps/session-server"
DEV_VARS="$SESSION_SERVER_DIR/.dev.vars"

# Shared dev OAuth app (public — client ID is not a secret)
DEV_CLIENT_ID="Ov23liNnbDyIs6wu4Btd"

echo "=== Shipyard Session Server Setup ==="
echo ""

# Step 1: Create or validate .dev.vars
if [ -f "$DEV_VARS" ]; then
  echo "✓ .dev.vars already exists"

  # Check if all required vars are populated
  MISSING=()
  grep -q "^GITHUB_CLIENT_ID=.\+" "$DEV_VARS" || MISSING+=("GITHUB_CLIENT_ID")
  grep -q "^GITHUB_CLIENT_SECRET=.\+" "$DEV_VARS" || MISSING+=("GITHUB_CLIENT_SECRET")
  grep -q "^JWT_SECRET=.\+" "$DEV_VARS" || MISSING+=("JWT_SECRET")

  if [ ${#MISSING[@]} -gt 0 ]; then
    echo "  ⚠️  Missing values: ${MISSING[*]}"
    echo "  Edit: $DEV_VARS"
  else
    echo "  ✓ All required secrets are set"
  fi
else
  echo "Creating .dev.vars..."

  JWT_SECRET=$(openssl rand -base64 32)

  cat > "$DEV_VARS" << VARS
# Auto-generated by scripts/setup-session-server.sh
# Shared development OAuth app — ask a team member for the client secret
GITHUB_CLIENT_ID=$DEV_CLIENT_ID
GITHUB_CLIENT_SECRET=
JWT_SECRET=$JWT_SECRET
VARS

  echo "✓ Created .dev.vars with:"
  echo "  ✓ GITHUB_CLIENT_ID (shared dev app)"
  echo "  ✓ JWT_SECRET (auto-generated)"
  echo "  ⚠️  GITHUB_CLIENT_SECRET is blank — ask a team member or check 1Password"
fi

echo ""

# Step 2: Apply D1 migrations locally
echo "Applying D1 migrations locally..."
cd "$SESSION_SERVER_DIR"

if command -v wrangler &> /dev/null; then
  wrangler d1 migrations apply shipyard-users --local 2>/dev/null || {
    echo "  Note: migrations may already be applied, or wrangler dev will apply them."
  }
  echo "✓ D1 migrations applied"
else
  npx wrangler d1 migrations apply shipyard-users --local 2>/dev/null || {
    echo "  Note: migrations may already be applied, or wrangler dev will apply them."
  }
  echo "✓ D1 migrations applied (via npx)"
fi

echo ""
echo "=== Setup Complete ==="
echo ""

# Only show next steps that are actually needed
if [ -f "$DEV_VARS" ] && grep -q "^GITHUB_CLIENT_SECRET=$" "$DEV_VARS" 2>/dev/null; then
  echo "Next steps:"
  echo "  1. Add GITHUB_CLIENT_SECRET to $DEV_VARS"
  echo "  2. Start the server: pnpm dev:session-server"
  echo "  3. Login the daemon: shipyard login"
else
  echo "Ready! Run:"
  echo "  pnpm dev:session-server"
  echo "  shipyard login  (in another terminal)"
fi
echo ""
